### PR TITLE
use word wrap instead of scroll

### PR DESCRIPTION
**Pull request by lcruz4**
image

### CODE REVIEW

**Review by dmccloud — APPROVED** [review]
Dis why you principal

you’re a prince and you’re my pal 

do we need the min-w-0?

**Comment by lcruz4** [comment]
> Dis why you principal
> 
> you’re a prince and you’re my pal
> 
> do we need the min-w-0?

you dare question me 😤😤😤

**Comment by dmccloud** [comment]
> > Dis why you principal
> > you’re a prince and you’re my pal
> > do we need the min-w-0?
> 
> you dare question me 😤😤😤

I approved. Quit yet bitchin and merge this 💩

**Comment by lcruz4** [comment]
> > > Dis why you principal
> > > you’re a prince and you’re my pal
> > > do we need the min-w-0?
> > 
> > 
> > you dare question me 😤😤😤
> 
> I approved. Quit yet bitchin and merge this 💩

imma close it out of spite!!!!!

**Pull request merged**
